### ISSUE TITLE
DEV TASK: Set Up Project Planning

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#1]
As a **developer**, I can **set up my project planning environments** so that I can **start working on my project and keep track of it's development**.

# **Tasks**

- [ ] Set up GitHub Projects Kanban Board
- [ ] Set up the environment for PP5
- [ ] Design  wireframes for PP5
- [ ] Set up Lucidchart for ERD
