### ISSUE TITLE
USER STORY:  Search Function

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#10]
As a **user**, I can **enter text into the search bar** so that I can **search for a specific item**.

# **Acceptance Criteria**:

- Search bar is visible in navigation area.
- Placeholder text in the search field informs the user to enter text.
- Search function brings user to the correct item searched.

# **Tasks**:
- [ ]  Add search bar to navigation area
- [ ]  Adjust default bootstrap styling
- [ ]  Add search functionality to view.py
- [ ]  Test search bar
