### ISSUE TITLE
USER STORY: User Account Registration 

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#12]
As a **user** I want to be able to **register an account** so that I can have **access to all functionality of Hookah Culture**.

# **Acceptance Criteria**:
- A "Sign Up" button on the navigation menu should be visible for an unregistered user when visit the website.
- A form with fields to enter my username, email address, and password should be displayed after being redirected to the registration page.
- A "Registration Successful" page should appear after filling in the registration form with valid information.
- After logging in with my own credentials, I should have access to all the functionalities of Hookah Culture.

# **Tasks**: 

- [ ]  Design and implement the frontend template for the navigation menu, including a "Sign Up" button.
- [ ] Install and configure django-allauth
- [ ] Create a registration form template provided by django-allauth for user account registration.
- [ ] Implement URL routing to direct users to the registration page.
- [ ] Configure email confirmation and account activation settings provided by django-allauth.
- [ ] Design and implement the frontend template for the "Registration Successful" page or notification.
