### ISSUE TITLE
USER STORY: User Login

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#13]
As a **user**, I want to be able to **log in to my account** so that I can **access my personalized features and make purchases on Hookah Culture**.

# **Acceptance Criteria**:
- A "Log In" button on the navigation menu should be visible for registered users when they visit the website.
- A form with fields to enter my username or email address and password should be visible for registered users when they click on the "Log In" button after being redirected to the login page.
- After successfully submitting the login form, a registered user with valid login credentials should be redirected to my profile page or the landing page.
- An appropriate error message indicating that the login attempt was unsuccessful should appear after a registered user enters invalid login credentials.
- A full access to all my personalized features should be visible for a logged-in user.
- A logout button in the navbar should be displayed instead of Login button for a registered and logged in user.

# **Tasks**:
- [ ] Design and implement the frontend template for the navigation menu, including a "Log In" button.
- [ ] Create a login form template for user authentication.
- [ ] Implement URL routing to direct users to the login page.
- [ ] Design and implement the frontend template for the "Login Successful" page or notification.
- [ ] Test the login process to verify that users can successfully log in with valid credentials.
