### ISSUE TITLE
USER STORY: User Password Reset 

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#14]
As a **registered user** I want to be able to **reset my password** so that I can **regain access to my account in case I forget my password**.

# **Acceptance Criteria**:

- A "Forgot Password" link should be visible for a registered user when being on the login page.
- A password reset page should appear with a form where I can enter my email address to initiate the password reset process  for a registered user after clicking on the "Forgot Password" link.
- An email with instructions on how to reset the password should be received after submitting the form where the email is written on the form as a  registered user.
- A confirmation message should be received after submitting the form with the new password on the password reset page as a registered user.

# **Tasks**:
- [ ] Implement forgot password link on the login page.
- [ ] Create url for reset password, email sent, enter new password and password changed successfully.
- [ ] Create templates for reset password, email sent, enter new password and password changed successfully.
