### ISSUE TITLE
USER STORY: View/ Edit My Profile

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#15]
As a **registered user**  I want to be able to **see my profile page** so that I can **update my information**.

# **Acceptance Criteria**:
- As a registered user, when I log in to my account,  I should be able to access my profile page.
- As a registered user I should see my personal information on my profile page.
- As a registered user when I update my information through the profile page, the changes should be saved and reflected on my profile.
- As a registered user when I click on the "Edit Profile" button,  I should be able to edit my information.
- As a registered user when I submit the updated information,  the changes should be saved and applied to my profile, and I should receive a confirmation message.

# **Tasks**:
 - [ ] Define the url for the profile page.
 - [ ] Create the view that renders the profile page.
 - [ ] Create the option to edit the profile details.
 - [ ] Create the view that handles the edit form.
 - [ ] Ensure there is an edit button on the profile page.
