### ISSUE TITLE
DEV TASK:  Initial Django Setup

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#2]
As a **developer** I can **setup a new Django project** so that I can **create the project's structure**.

#**Tasks**:

- [ ] Install Django through the package manager
- [ ] Create new project with the name HOOKAH CULTURE
- [ ] Create the first app and add it to settings.py
- [ ] Create env.py file to hide the secret keys
- [ ] Add env.py to .gitignore so that the secret keys stay private
