### ISSUE TITLE
USER STORY: Edit Reviews

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#28]
As a an **authenticated user** I want to be able to **edit my reviews for a product** so that I can **manage and maintain the accuracy and relevance of my feedback**.

# **Acceptance Criteria**:

- As a logged-in user, when I am viewing a product's review section, I should see my reviews with an option to edit the review.
- As a user, I am viewing a product's review section, when I click on the edit button, I should be redirected to a page to edit my review.
- As a user, I am on the edit review page, when I edit my review, I should see a button to submit my updated review.
- As a user, I am on the edit review page, when I submit my updated review, I should see a clear message indicating if the action was successful.

# **Tasks**:
- [ ] Create a template to render the edit review form.
- [ ] Create a view to display the edit view page and handle the submission of the form.
- [ ] Redirect the user to the product page while displaying clear message on the success or fail of the action.
