### ISSUE TITLE
USER STORY: Delete Reviews

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#29]
As a an **authenticated user** I want to be able to **delete my reviews for a product** so that I can **manage and maintain the accuracy and relevance of my feedback**.

# **Acceptance Criteria**:

- As a logged-in user, when I am viewing a product's review section, I should see my reviews with an option to delete the review.
- As a user, I am viewing a product's review section, when I click on the delete button, I should see my review being deleted with a clear message.

# **Tasks**:
- [ ] Create a form with delete button, visible to super users and users who created the review in the template.
- [ ] Create the view to handle the process of deleting a review.
- [ ] Display clear feedback message to the user based on the success or fail of the action.
