### ISSUE TITLE
DEV TASK: Connect database and media storage

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#3]
As a **developer** I can **connect database and media storage** so that **the user's stored data is stored successfully**.

# **Tasks**:

- [ ] Install required packages.
- [ ] Configure Django's settings to connect to database.
- [ ] Configure setting for ElephantSQL.
- [ ] Configure settings for static files.
- [ ] Configure AWS settings.
- [ ] Configure Django's settings to connect to AWS.
- [ ] Create superuser and run migrations.
- [ ] Test database and media storage.
