### ISSUE TITLE
USER STORY: Mailchimp Newsletter

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#30]
As a **user**, I want to **sign up for newsletters** on the website so that I can **keep up with updates and deals**.

# **Acceptance Criteria**:

- As a user, when I visit the website, I should see a clear and accessible option to subscribe to newsletters on the homepage or footer.
- As a user, when I submit the subscribe form with my email, I should see confirmation message.

# **Tasks**:
- [ ] Create an account on Mailchimp website.
- [ ] Copy the code for the form into the footer.
- [ ] Test that the form works correctly.
