### ISSUE TITLE
USER STORY - Contact Us 

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#31]
As a **user**, I can submit  **Contact Us form** so I can **send a message to the business/site admin**.

# **Acceptance Criteria**:

- As a user, I should be able to easily see a Contact form.
- As a user, I should be able to submit my question through the Contact Form.
- As a user, I should receive a confirmation message after submitting my questions on the  Contact Form.

# **Tasks**:
- [ ] Create questions model and its relevant fields.
- [ ] Connect contact form using contexts.py.
- [ ] Test connection of contact form to website email account.
