### ISSUE TITLE
USER STORY: Checkout functionality

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#33]
As a **user**, I want to be able to **complete the checkout process for my shopping cart** so that I can **purchase the items I've added to my cart**.

# **Acceptance Criteria**:

- As a user, I'm on the checkout page, when I review my cart contents,  I should see a summary of items in my cart, including their names, quantities, prices, and total cost.
- As a user, I need to provide my delivery and billing information, when I enter this information, I should see fields for full name, email, phone number and shipping address.
- As a user, my order total meets or exceeds the "FREE DELIVERY" threshold, when the delivery cost is calculated, then it should be displayed as €0.

# **Tasks**:
- [ ] Create checkout app and order models.
- [ ]  Create a checkout page that displays cart's content.
- [ ]  Implement a form to collect and validate user's billing and delivery information.
- [ ]  Implement the logic to determine the delivery cost based on the amount spent.
- [ ]  Implement the logic to calculate the order total.
