### ISSUE TITLE
DEV TASK: Document Testing Process

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#34]
As a **developer**, I can thoroughly **test all aspects of my project** so that I can **make sure the user has the correct experience and receives no errors**.

# **Acceptance Criteria**:

- TESTING.md is written up to include every feature and aspect of project:
Responsiveness
Browser Compatibility
Lighthouse
Code Validation
User stories
Features
Automated testing (Optional)
- All features work as expected.

# **Tasks**:
 - [ ] Test all input and validation.
 - [ ] Validate all HMTL, CSS, JS and Python.
 - [ ] Write up TESTING.md with screenshots.
