### ISSUE TITLE
DEV TASK - Complete README for Hookah Culture

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#35]
As a **developer**, I can **record all of my project information in my README.md** so that I can **document my work for myself and others**.

# **Acceptance Criteria**:

- I want to be able to see all the information about the project.

# **Tasks**:

- Add the following sections to README.MD:

- [ ] Overview
- [ ] Project Goals
- [ ] UX
- [ ] The Strategy Plane
- [ ] The Ideal User
- [ ] Site Goals
- [ ] Agile Planning
- [ ] Epics
- [ ] User Stories
- [ ] The Skeleton Plane
- [ ] Wireframes
- [ ] Database Schema
- [ ] Features
- [ ] Future Features
- [ ] Design
- [ ] Colour Scheme
- [ ] Typography
- [ ] Imagery
- [ ] Technologies Used
- [ ] Languages Used
- [ ] Frameworks and Tools Used
- [ ] Libraries Used
- [ ] Testing
- [ ] Deployment
- [ ] Credits
- [ ] Acknowledgements
