### ISSUE TITLE
DEV TASK:  Initial deployment

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#4]
As a **developer** I can **deploy the application early** so that I can **confirm that the initial setup is working and  continue testing the application during development**. 

# **Tasks**:

- [ ] Create new app on Heroku.
- [ ] Add all secret keys to config vars.
- [ ] Create requirements.txt file.
- [ ] Create Procfile.
- [ ] Deploy to Heroku and test if the application runs with no errors.
