### ISSUE TITLE
USER STORY - Site Navigation 

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#5]
As a **user**, I can **see and use the navigation bar** so that I can **make my way around the site and get to where I would like**.

# **Acceptance Criteria**:

- Navigation bar is visible and responsive to all screen sizes.
- Logo is present and returns user to home page.
- Navigation options are clickable and display which page the user is on.
- Links bring user to the correct area.
- Search field is visible in the navbar.
- Footer displays additional navigational qualities as well as business information.

# **Tasks**:

- [ ] Design the navigation bar.
- [ ] Ensure the navigation bar is fully responsive.
- [ ] Ensure all links in the navigation bar redirect to the correct page.
