### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#6]
As a **user** I can **view and visit the home page** so that I can **identify the purpose of the website**.

# **Acceptance Criteria**:

- User can view the home page when website loads.
- Home page navigation area and footer are visible.
- Business details are displayed.

# **Tasks**:

 - [ ] Create base.html
- [ ] Connect base.html to index.html
- [ ] Provide basic information, formatting and styling to the page
- [ ] Add favicon
- [ ] Add header/footer html
