### ISSUE TITLE
USER STORY: All products view

### ISSUE THREAD

**Issue by Delfinistkata** [Delfinistkata/hookah_culture#7]
As a **user** I want to be able to **view a list of all available products in the website**  so that I can **browse and choose the product to purchase**

# **Acceptance Criteria**:

- A paginated list of all available products should be displayed after clicking on "All Products". in the navigation menu.
- A product card should be displayed on the "All Products" page and it should contain the following information:
The product's name
The product's colour
The product's image
The product's price
The product's quantity
An "Add to Cart" button

- A product detail page should open when clicked on product card, where all the related information can be seen for that product.

# **Tasks**:

- [ ] Create a Django view for displaying all products.
- [ ] Create a template for the "All Products" page to render the list of products.
- [ ] Create a product model in the database with the relevant fields.
- [ ] Implement pagination for the list of products to display a reasonable number per page.
- [ ] Create a "Browse All Products" link in the navigation menu that points to the "All Products" view.
- [ ] Ensure proper URL routing for the "All Products" page.
- [ ] Implement and style the product cards on the "All Products" page.
